[build]
  # Build command (not needed for static sites, but can be useful for future expansion)
  command = "echo 'Static site - no build needed'"
  
  # Directory to publish (current directory since index.html is in root)
  publish = "."

[build.environment]
  # Node.js version for any future build processes
  NODE_VERSION = "18"

# Redirect rules for SPA-like behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Form handling (if you add contact forms later)
# [[redirects]]
#   from = "/contact"
#   to = "/.netlify/functions/contact"
#   status = 200
#   methods = ["POST"]
